kind: pipeline
type: docker
name: default
trigger:
  branch: master

steps:
  - name: golangci-lint
    image: golangci/golangci-lint:latest
    depends_on:
      - clone
    environment:
      GOOS: js
      GOARCH: wasm
    commands:
      - golangci-lint run

  - name: test
    image: "golang:1.16.5-alpine3.13"
    commands:
      - apk add --no-cache wget
      - wget https://taskfile.dev/install.sh
      - sh install.sh -- latest
      - rm install.sh
      - ./bin/task test
